name: MediaControl
options:
  bundleIdPrefix: com.mediacontrol
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true

packages:
  MediaControl:
    path: .

targets:
  MediaControl:
    type: application
    platform: macOS
    sources:
      - MediaControlApp
    dependencies:
      - package: MediaControl
        product: ShieldClient
      - package: MediaControl
        product: OnkyoClient
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mediacontrol.app
        PRODUCT_NAME: MediaControl
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: MediaControlApp/Info.plist
        SWIFT_VERSION: "5.9"
      configs:
        Debug:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Apple Development"
          DEVELOPMENT_TEAM: WHS8S6ZW43
          ENABLE_HARDENED_RUNTIME: YES
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application: SWACKTECH, LLC (WHS8S6ZW43)"
          DEVELOPMENT_TEAM: WHS8S6ZW43
          OTHER_CODE_SIGN_FLAGS: --timestamp
          ENABLE_HARDENED_RUNTIME: YES
          CODE_SIGN_ENTITLEMENTS: MediaControlApp/Release.entitlements
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
    scheme:
      testTargets: []
